/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description API status plus what the runner reports (cached for a few seconds).
         */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/languages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Languages
         * @description Languages this deployment supports, with their toolchains and limits.
         *
         *     `available` tells the editor which ones can run right now: a language whose
         *     sandbox image is not installed on the runner is listed but not offered.
         *     Profiles that are not languages of their own (the notebook runner) are not
         *     listed; they can still be run by id.
         */
        get: operations["list_languages_api_v1_languages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/executions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Execution
         * @description Queue a compile-and-run of the given source. Returns immediately.
         */
        post: operations["create_execution_api_v1_executions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/executions/{execution_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Execution */
        get: operations["get_execution_api_v1_executions__execution_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assistant/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Assistant Status */
        get: operations["assistant_status_api_v1_assistant_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assistant/explain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Explain
         * @description Explain a diagnostic of a finished run, grounded in that run's evidence.
         */
        post: operations["explain_api_v1_assistant_explain_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assistant/fix": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Fix
         * @description Propose the smallest patch for a diagnostic. The student must approve it.
         */
        post: operations["fix_api_v1_assistant_fix_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assistant/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify
         * @description Decide from a real run of the patched code whether a fix worked.
         */
        post: operations["verify_api_v1_assistant_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assistant/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask
         * @description Answer a question about programming, the editor's code or a run.
         */
        post: operations["ask_api_v1_assistant_ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assistant/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Complete
         * @description Suggest what comes next at the cursor (the editor shows it as ghost text; Tab accepts).
         */
        post: operations["complete_api_v1_assistant_complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AskIn */
        AskIn: {
            /** Question */
            question: string;
            /** Languageid */
            languageId?: string | null;
            /**
             * Executionid
             * @description Ground the answer in this run (source, diagnostics, output).
             */
            executionId?: string | null;
            /** Sourcehash */
            sourceHash?: string | null;
            /**
             * Source
             * @description The editor's code when there is no run to ground the answer in.
             */
            source?: string | null;
            /** History */
            history?: components["schemas"]["ChatTurnIn"][];
        };
        /** AskOut */
        AskOut: {
            /** Answer */
            answer: string;
            /**
             * Groundedon
             * @enum {string}
             */
            groundedOn: "execution" | "source" | "none";
            /** Executionid */
            executionId?: string | null;
            /** Sourcehash */
            sourceHash?: string | null;
            /** Provider */
            provider: string;
            /** Model */
            model: string;
            /**
             * Cached
             * @default false
             */
            cached: boolean;
        };
        /** AssistantStatusOut */
        AssistantStatusOut: {
            /**
             * Enabled
             * @description False when no AI provider is configured; the rest of the app still works.
             */
            enabled: boolean;
            /** Provider */
            provider?: string | null;
            /** Model */
            model?: string | null;
            /**
             * Reason
             * @description Why Saarthi is unavailable, in plain words.
             */
            reason?: string | null;
            /** Requestsperminute */
            requestsPerMinute: number;
            /** Requestsperday */
            requestsPerDay: number;
        };
        /**
         * Category
         * @enum {string}
         */
        Category: "syntax" | "name" | "type" | "build" | "runtime" | "timeout" | "memory" | "other";
        /** ChatTurnIn */
        ChatTurnIn: {
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant";
            /** Content */
            content: string;
        };
        /** CodeLocationOut */
        CodeLocationOut: {
            /** Line */
            line: number;
        };
        /**
         * CompleteIn
         * @description Code around the editor's cursor, for an inline completion (ghost text).
         */
        CompleteIn: {
            /** Languageid */
            languageId: string;
            /**
             * Prefix
             * @description The code before the cursor.
             */
            prefix: string;
            /**
             * Suffix
             * @description The code after the cursor.
             * @default
             */
            suffix: string;
            /**
             * Maxlines
             * @default 4
             */
            maxLines: number;
        };
        /** CompleteOut */
        CompleteOut: {
            /**
             * Completion
             * @description Text to insert at the cursor; empty when the model has nothing useful.
             */
            completion: string;
            /** Provider */
            provider: string;
            /** Model */
            model: string;
            /**
             * Cached
             * @default false
             */
            cached: boolean;
        };
        /** Diagnostic */
        Diagnostic: {
            /** Id */
            id: string;
            source: components["schemas"]["DiagnosticSource"];
            severity: components["schemas"]["Severity"];
            category: components["schemas"]["Category"];
            /**
             * Code
             * @description Stable identifier, e.g. C_UNDECLARED_IDENTIFIER, RUNTIME_SEGMENTATION_FAULT, UNPARSED
             */
            code: string;
            /** Message */
            message: string;
            /**
             * File
             * @description Workspace-relative path, e.g. main.c
             */
            file?: string | null;
            range?: components["schemas"]["SourceRange"] | null;
            /** Relatedlocations */
            relatedLocations?: components["schemas"]["RelatedLocation"][];
            /** Executionid */
            executionId?: string | null;
            rawOutputReference?: components["schemas"]["RawOutputReference"] | null;
        };
        /**
         * DiagnosticSource
         * @enum {string}
         */
        DiagnosticSource: "local" | "compiler" | "runtime";
        /** ErrorOut */
        ErrorOut: {
            /** Detail */
            detail: string;
            /** Retryafters */
            retryAfterS?: number | null;
        };
        /** ExecutionCreate */
        ExecutionCreate: {
            /**
             * Languageid
             * @example c
             */
            languageId: string;
            /**
             * Source
             * @description Exact editor contents; its SHA-256 identifies this snapshot.
             */
            source: string;
            /**
             * Stdin
             * @description Text given to the program on standard input.
             * @default
             */
            stdin: string;
        };
        /** ExecutionOut */
        ExecutionOut: {
            /** Id */
            id: string;
            /** Languageid */
            languageId: string;
            state: components["schemas"]["ExecutionState"];
            /** Terminal */
            terminal: boolean;
            /**
             * Summary
             * @description One-line, plain-language status for the UI.
             */
            summary: string;
            /**
             * Sourcehash
             * @description sha256:<hex> of the exact source that was (or will be) compiled.
             */
            sourceHash: string;
            /** Sourcebytes */
            sourceBytes: number;
            /**
             * Queueposition
             * @description 1-based position while QUEUED.
             */
            queuePosition?: number | null;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Startedat */
            startedAt?: string | null;
            /** Finishedat */
            finishedAt?: string | null;
            toolchain?: components["schemas"]["ToolchainOut"] | null;
            /** Steps */
            steps: components["schemas"]["ExecutionStepOut"][];
            /** Diagnostics */
            diagnostics: components["schemas"]["Diagnostic"][];
            /** Error */
            error?: string | null;
        };
        /**
         * ExecutionState
         * @enum {string}
         */
        ExecutionState: "QUEUED" | "STARTING" | "COMPILING" | "RUNNING" | "SUCCEEDED" | "COMPILE_ERROR" | "RUNTIME_ERROR" | "TIMEOUT" | "MEMORY_LIMIT" | "REJECTED" | "CANCELLED" | "INTERNAL_ERROR";
        /** ExecutionStepOut */
        ExecutionStepOut: {
            /** Name */
            name: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "compile" | "run";
            status: components["schemas"]["StepStatus"];
            /** Termination */
            termination?: string | null;
            /** Exitcode */
            exitCode?: number | null;
            /** Signal */
            signal?: number | null;
            /** Signalname */
            signalName?: string | null;
            /** Durationms */
            durationMs?: number | null;
            /** Wallms */
            wallMs?: number | null;
            /**
             * Stdout
             * @default
             */
            stdout: string;
            /**
             * Stderr
             * @default
             */
            stderr: string;
            /**
             * Stdouttruncated
             * @default false
             */
            stdoutTruncated: boolean;
            /**
             * Stderrtruncated
             * @default false
             */
            stderrTruncated: boolean;
            /** Peakmemorybytes */
            peakMemoryBytes?: number | null;
            limits: components["schemas"]["StepLimitsOut"];
        };
        /** ExplainIn */
        ExplainIn: {
            /** Executionid */
            executionId: string;
            /**
             * Sourcehash
             * @description Hash of the code in the editor; must match the run (no stale answers).
             */
            sourceHash: string;
            /**
             * Diagnosticid
             * @description Diagnostic to explain; default: the first error.
             */
            diagnosticId?: string | null;
            /** Question */
            question?: string | null;
        };
        /** ExplanationOut */
        ExplanationOut: {
            /** Executionid */
            executionId: string;
            /**
             * Sourcehash
             * @description The explanation applies to exactly this source.
             */
            sourceHash: string;
            /** Focusdiagnosticid */
            focusDiagnosticId: string | null;
            /**
             * Diagnosticids
             * @description The diagnostics Saarthi was shown (its evidence).
             */
            diagnosticIds: string[];
            /** Problem */
            problem: string;
            /** Whathappened */
            whatHappened: string;
            /** Why */
            why: string;
            location: components["schemas"]["CodeLocationOut"] | null;
            /** Suggestedfix */
            suggestedFix: string;
            /** Relatedconcepts */
            relatedConcepts: string[];
            /**
             * Confidence
             * @enum {string}
             */
            confidence: "low" | "medium" | "high";
            /**
             * Verified
             * @description Explanations are advice; only a run verifies code.
             * @default false
             * @constant
             */
            verified: false;
            /** Provider */
            provider: string;
            /** Model */
            model: string;
            /**
             * Cached
             * @default false
             */
            cached: boolean;
        };
        /** FixIn */
        FixIn: {
            /** Executionid */
            executionId: string;
            /** Sourcehash */
            sourceHash: string;
            /** Diagnosticid */
            diagnosticId?: string | null;
        };
        /** FixOut */
        FixOut: {
            /**
             * Fixid
             * @description Pass to /assistant/verify after running the patched code.
             */
            fixId: string;
            /** Executionid */
            executionId: string;
            /**
             * Basesourcehash
             * @description The patch applies to exactly this source.
             */
            baseSourceHash: string;
            /** Patchedsource */
            patchedSource: string;
            /** Patchedsourcehash */
            patchedSourceHash: string;
            /** Summary */
            summary: string;
            /** Edits */
            edits: components["schemas"]["PatchEditOut"][];
            /**
             * Targetcodes
             * @description Diagnostic codes the fix is meant to remove.
             */
            targetCodes: string[];
            /**
             * Confidence
             * @enum {string}
             */
            confidence: "low" | "medium" | "high";
            /**
             * Verified
             * @description Not verified until the patched code is run.
             * @default false
             * @constant
             */
            verified: false;
            /** Provider */
            provider: string;
            /** Model */
            model: string;
            /**
             * Cached
             * @default false
             */
            cached: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LanguageOut */
        LanguageOut: {
            /** Id */
            id: string;
            /** Displayname */
            displayName: string;
            /** Editormode */
            editorMode: string;
            /** Sourcefile */
            sourceFile: string;
            toolchain: components["schemas"]["LanguageToolchainOut"];
            /** Steps */
            steps: components["schemas"]["LanguageStepOut"][];
            /**
             * Status
             * @description "experimental": prepared but not yet verified end to end (shown with a badge).
             * @default stable
             * @enum {string}
             */
            status: "stable" | "experimental";
            /**
             * Available
             * @description Whether the sandbox runner has this language's toolchain image installed. null when the runner cannot be reached right now.
             */
            available?: boolean | null;
        };
        /** LanguageStepOut */
        LanguageStepOut: {
            /** Name */
            name: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "compile" | "run";
            /**
             * Label
             * @description Shown in the run pipeline, e.g. "Compile" or "Syntax check".
             */
            label: string;
            /**
             * Argv
             * @description The exact trusted command, shown to students for transparency.
             */
            argv: string[];
            limits: components["schemas"]["StepLimitsOut"];
        };
        /** LanguageToolchainOut */
        LanguageToolchainOut: {
            /** Name */
            name: string;
            /** Declaredversion */
            declaredVersion: string;
            /** Image */
            image: string;
        };
        /** PatchEditOut */
        PatchEditOut: {
            /**
             * Startline
             * @description First replaced line (1-based, in the original source).
             */
            startLine: number;
            /**
             * Endline
             * @description Last replaced line, inclusive.
             */
            endLine: number;
            /**
             * Replacement
             * @description The new lines; empty deletes the range.
             */
            replacement: string;
        };
        /**
         * RawOutputReference
         * @description Where in the bounded raw output this diagnostic came from (1-based lines).
         */
        RawOutputReference: {
            /** Step */
            step: string;
            /**
             * Stream
             * @enum {string}
             */
            stream: "stdout" | "stderr";
            /** Startline */
            startLine: number;
            /** Endline */
            endLine: number;
        };
        /** RelatedLocation */
        RelatedLocation: {
            /** File */
            file?: string | null;
            range?: components["schemas"]["SourceRange"] | null;
            /** Message */
            message: string;
        };
        /**
         * Severity
         * @enum {string}
         */
        Severity: "error" | "warning" | "info";
        /** SourceRange */
        SourceRange: {
            /** Startline */
            startLine: number;
            /** Startcolumn */
            startColumn: number;
            /** Endline */
            endLine: number;
            /** Endcolumn */
            endColumn: number;
        };
        /** StepLimitsOut */
        StepLimitsOut: {
            /** Walltimems */
            wallTimeMs: number;
            /** Memorymb */
            memoryMb: number;
            /** Outputkb */
            outputKb: number;
        };
        /**
         * StepStatus
         * @enum {string}
         */
        StepStatus: "PENDING" | "RUNNING" | "SUCCEEDED" | "FAILED" | "SKIPPED";
        /** ToolchainOut */
        ToolchainOut: {
            /** Name */
            name: string;
            /**
             * Version
             * @description Exact version read from the sandbox image; null if unknown.
             */
            version: string | null;
            /** Image */
            image: string;
            /** Imageid */
            imageId?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VerifyIn */
        VerifyIn: {
            /** Fixid */
            fixId: string;
            /**
             * Executionid
             * @description The run of the patched code.
             */
            executionId: string;
        };
        /** VerifyOut */
        VerifyOut: {
            /** Fixid */
            fixId: string;
            /** Executionid */
            executionId: string;
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "fixed" | "improved" | "not_fixed" | "different_code";
            /**
             * Verified
             * @description True only when the run of the patched code finished without errors.
             */
            verified: boolean;
            /** Message */
            message: string;
            /** Beforestate */
            beforeState: string;
            /** Afterstate */
            afterState: string;
            /** Beforeerrors */
            beforeErrors: number;
            /** Aftererrors */
            afterErrors: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_languages_api_v1_languages_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LanguageOut"][];
                };
            };
        };
    };
    create_execution_api_v1_executions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExecutionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExecutionOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    get_execution_api_v1_executions__execution_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                execution_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExecutionOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assistant_status_api_v1_assistant_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssistantStatusOut"];
                };
            };
        };
    };
    explain_api_v1_assistant_explain_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExplainIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExplanationOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    fix_api_v1_assistant_fix_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FixIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FixOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    verify_api_v1_assistant_verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerifyOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    ask_api_v1_assistant_ask_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    complete_api_v1_assistant_complete_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompleteIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompleteOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
}
